version: '3.8'

services:
    unbinder-client:
        depends_on:
            - unbinder-db
        container_name: unbinder-client
        build:
            context: .
            dockerfile: ./Docker/DOTNET.Dockerfile
        ports:
            - ${CLIENT_PORT}:80
            - 8080:8080
        environment:
            CLIENT_PORT: /run/secrets/CLIENT_PORT
            SA_PASSWORD: /run/secrets/SA_PASSWORD
            AWS_S3_URL: /run/secrets/AWS_S3_URL
            AWS_ACCESS_KEY: /run/secrets/AWS_ACCESS_KEY
            AWS_SECRET_KEY: /run/secrets/AWS_SECRET_KEY
            AWS_BUCKET_NAME: /run/secrets/AWS_BUCKET_NAME
        networks:
            database:
    unbinder-db:
        container_name: unbinder-db
        build:
            context: .
            dockerfile: ./Docker/MSSQL.Dockerfile
        ports:
            - 1433:1433
        environment:
            SA_PASSWORD: /run/secrets/SA_PASSWORD
        volumes:
            - ./db_data:/var/opt/mssql/data
        networks:
          database:
            aliases:
              - unbinder-db

networks:
    database:
        driver: bridge

secrets:
    CLIENT_PORT:
        file: ./secrets/CLIENT_PORT.txt
    AWS_S3_URL:
        file: ./secrets/AWS_S3_URL.txt
    AWS_ACCESS_KEY:
        file: ./secrets/AWS_ACCESS_KEY.txt
    AWS_SECRET_KEY:
        file: ./secrets/AWS_SECRET_KEY.txt
    AWS_BUCKET_NAME:
        file: ./secrets/AWS_BUCKET_NAME.txt
    SA_PASSWORD:
        file: ./secrets/SA_PASSWORD.txt

volumes:
    db_data: